### ISSUE TITLE
请问一下运行问题

### ISSUE THREAD

**Issue by Arashiailing** [ShangRui-hash/siusiu#4]
师傅你好，想请问一下，windows环境下
 go build -o siusiu后 再执行这条指令 就没有回显 应该是build成功了嘛
然后 还需要什么指令嘛
因为 执行help指令也没用 docker里也没有看见容器运行orz

**Comment by ShangRui-hash** [comment]
可以看下当前目录下是否有 siusiu 可执行文件

**Comment by Arashiailing** [comment]
有siusiu无后缀文件，添加后缀exe倒是可以运行，但是里面的工具会报错，我换成Mac试试吧 蟹蟹师傅
