### ISSUE TITLE
xray reverse 初始化失败

### ISSUE THREAD

**Issue by haihong-yu** [ShangRui-hash/siusiu#8]
![image](https://github.com/ShangRui-hash/siusiu/assets/104617396/d9c1d884-8ee6-48e1-97f4-2b81ebc3fec1)
以下是我的配置文件
![image](https://github.com/ShangRui-hash/siusiu/assets/104617396/69639b6c-688d-41ae-b6b2-973dc7111e59)

**Comment by ShangRui-hash** [comment]
Hi, xray 高级版的许可证已经过期了（this license is expired, expiration time is 2022-08-03 00:00:00），之后将会考虑从工具箱中移除该xray 镜像
